# -*- coding: utf-8 -*-
"""Variables.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xPGUmS79MXLfm4XP4tzCWLULlf-uqWAY
"""

# Create a variable called break and assign it a value 5. See what happens and find out the reason behind the behavior that you see
break = 5

"""The break statement terminates the loop containing it."""

#. Create two variables. One to store your birth year and another one to store current year. Now calculate your age using these two variables

birth_year = 1987
current_year = 2021
Age = current_year - birth_year
Age


# Store your first, middle and last name in three different variables and then print your full name using these variables

first_name = "SAM"
last_name =  "ALEX"
middle_name = "BOURNE"
print(first_name + last_name + middle_name)

# Answer which of these are invalid variable names: "_nation, 1record, record1, record_one, record-one, record^one, continue"

_nation = 1

1record = 2

record1 = 3

record_one = 4

record-one = 5

record^one = 6

continue = 7

