# -*- coding: utf-8 -*-
"""2. Numbers.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10f9O6Z5YYDvkzYXaeONzqxCps2o3ndd5
"""

# Exercise
# 1. You have a football field that is 92 meter long and 48.8 meter wide. Find out total  area using python and print it

#For a square or rectangular ground, you will first need to measure the length and then the width of the ground. Multiply the length and width.

#Area = Length * Width

Length = 92
Breadth = 48.8
Area = Length * Breadth
Area

# 2. You bought 9 packets of potato chips from a store. Each packet costs 1.49 dollar and you gave shopkeeper 20 dollar.
#    Find out using python, how many dollars is the shopkeeper going to give you back?
packets = 9
cost_per_pack = 1.49
Cash_paid = 20

Total_cost = packets * cost_per_pack
Total_cost

Balance_amount = Cash_paid - Total_cost
Balance_amount

# 3. You want to replace tiles in your bathroom which is exactly square and 5.5 feet is its length. 
# If tiles cost 500 rs per square feet, how much will be the total cost to replace all tiles. Calculate and print the cost using python
#    Hint: Use power operator (**) to find area of a square

LENGTH_OF_SIDE = 5.5
AREA_OF_SQUARE = LENGTH_OF_SIDE * LENGTH_OF_SIDE 
AREA_OF_SQUARE

COST_PER_SQUARE_FEET = 500
TOTAL_COST = AREA_OF_SQUARE * COST_PER_SQUARE_FEET
TOTAL_COST

# 4. Print binary representation of number 17
num=17
print('Binary of number 17 is:', format(num,'b'))

