# -*- coding: utf-8 -*-
"""3. Strings.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TL5JPg8623FjQ0nnFS3eMNo9PVma3a94
"""

text = "Mangoes are tasty"

text

text [12:17]

text [0:7]

text[9]

text[1]

text [:13]

berry = ''' Python 
is not a difficult
Language '''

berry

Numeric_value = 99
String_values = "Look at the dogs out #"
shout = Numeric_value + String_values
shout

Numeric_value = 99
Numeric_value = str(Numeric_value)
String_values = "Look at the dogs out # "
shout = String_values + Numeric_value
shout

