# -*- coding: utf-8 -*-
"""4. Lists.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Lmgtj61zIT8mbVaBbmD4c_suJenN1b-s
"""

items = ["saving", "credit", "current" ]

items[0]

items[1] = "cheque"

items

items.append("credit cards")

items

items.insert(2, "debit cards")
items

stress = ["cibil", "score", "history"]

report = items + stress
report

"""You cannot add a string or a number to a list

You can add two lists
"""

"cheque" in items

"cheque" in stress

"cheque" in report

