# -*- coding: utf-8 -*-
"""5. If statement.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tmA3Cvi0orPS4GnJIHoMZHVpLJ0D6bDZ
"""

num = input ("Enter a number : ")
num = int(num)

if num %2==0:
  print("This an even number")
else:
  print("This is an odd number")

CAR = ["FERRARI", "LAMBORGHINI", "ROLLS-ROYCE", "AUDI", "BMW", "MUSTANG"]
BIKE = ["ENFIELD", "HARLEY", "DUCATI", "NINJA", "HONDA", "BAJAJ"]
PLANE = ["AIRBUS", "BOEING", "ROLLS-ROYCE", "GE"]

VEHICLE = input ("ENTER THE BRAND NAME :")

if VEHICLE in CAR :
  print("THIS IS A CAR")

elif VEHICLE in BIKE :
  print("THIS IS A BIKE")

elif VEHICLE in PLANE :
  print("THIS IS A PLANE")
else :
  print("NO IDEA BOSS !")

