# -*- coding: utf-8 -*-
"""5. If Statement Exercise.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dL1xUD0RH20msxKw0p-lIwrsGsVb228A
"""



"""Using following list of cities per country,
india = ["mumbai", "banglore", "chennai", "delhi"]
pakistan = ["lahore","karachi","islamabad"]
bangladesh = ["dhaka", "khulna", "rangpur"]


Write a program that asks user to enter a city name and it should tell which country the city belongs to

Write a program that asks user to enter two cities and it tells you if they both are in same country or not. 

For example if I enter mumbai and chennai, it will print "Both cities are in India" but if I enter mumbai and dhaka it should print "They don't belong to same country"
"""

india = ["mumbai", "banglore", "chennai", "delhi"] 
pakistan = ["lahore","karachi","islamabad"] 
bangladesh = ["dhaka", "khulna", "rangpur"]

city = input("Enter the name of the city :")

if city in india :
  print("This is in INDIA")
elif city in pakistan :
  print("This is in PAK")
elif city in bangladesh :
  print("This is in BANGS")
else :
  print ("I have not visited this place")

india = ["mumbai", "banglore", "chennai", "delhi"] 
pakistan = ["lahore","karachi","islamabad"] 
bangladesh = ["dhaka", "khulna", "rangpur"]

city1 = input("Enter the name of the first city :")
city2 = input("Enter the name of the second city :")

if city1 in india and city2 in india :
  print("These cities are in INDIA")
elif city1 in pakistan and city2 in pakistan :
  print("These cities are in PAK")
elif city1 in bangladesh and city2 in bangladesh :
  print("These cities are in BANGS")
else :
  print ("They both dont belong to same country")

"""2. Write a python program that can tell you if your sugar is normal or not. Normal fasting level sugar range is 80 to 100.


Ask user to enter his fasting sugar level
If it is below 80 to 100 range then print that sugar is low
If it is above 100 then print that it is high otherwise print that it is normal
"""

Sugar_level = input("Enter the sugar level :")
Sugar_level = int(Sugar_level)

if Sugar_level < 80 :
  print("Low sugar level ") 

elif Sugar_level > 100 :
  
  print("High sugar level ")
else :
  print("It is normal dude")



