# -*- coding: utf-8 -*-
"""6. For loop.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xlOzSYCRqFqQ1NqjuYDKfQsK_kVERuTW
"""

expenses = [2100, 2300, 2345, 2948, 2384]

total = 0
for xyz in expenses:
  total = total + xyz
  print(total)

for i in range(1,11):
  print(i)

for i in range(1,11):
  print(i**2)

expenses = [2100, 2300, 2345, 2948, 2384]
range(len(expenses))

expenses = [2100, 2300, 2345, 2948, 2384]

total = 0
for i in range(len(expenses)):
  print("MONTH :", (i+1), expenses[i])
  total = total + expenses[i]

print(total)

"""#RANGE FUNCTIONS"""

range(5)

a = range(5)
print(a)

print("JESUS LOVES YOU SO MUCH")

"""# FOR LOOP & IF CONDITION"""

job_loc = "New Jersey"
location = ["New York", "New Jersey", "Toronto", "Ottawa"]

for i in location:
  if i == job_loc:
    print("Location is in: ", i)
    break
  else :
    print("No idea ")

for i in range(1,11):
  if i%2==0:
    print(i**2)

"""# WHILE LOOP"""

i = 1
while i<=5:
  print(i)
  i = i+1

