# -*- coding: utf-8 -*-
"""Strings .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16vs7hB20zcv-sgOS80oH-XuJ870SFgFz

Create 3 variables to store street, city and country, now create address variable to store entire address. Use two ways of creating this variable, one using + operator and the other using f-string. Now Print the address in such a way that the street, city and country prints in a separate line
"""

stre ="A"
street = "B"
city = "C"
country = "us"
address = ''' stre \n street \n city \n country '''
address
print(address)

street = "13 patli gali"
city = "New Delhi"
country = "India"

address1 = street + '\n' + city + '\n' + country
print(address1)

address2 = f'{street}\n{city}\n{country}'
print(address2)

"""
Create a variable to store the string "Earth revolves around the sun"
Print "revolves" using slice operator
Print "sun" using negative index.


I have a string variable called s='maine 200 banana khaye'. This of course is a wrong statement, the correct statement is 'maine 10 samosa khaye'. Replace incorrect words in original strong with new ones and print the new string. Also try to do this in one line.
"""

earth_var = "Earth revolves around the sun"
earth_var[-3:]

"""

Create two variables to store how many fruits and vegetables you eat in a day. Now Print "I eat x veggies and y fruits daily" where x and y presents vegetables and fruits that you eat everyday. Use python f string for this.
"""

x = 3
y = 4
diet = print(f'I eat {x} veggies and {y} fruits daily') 
diet

s='hey\nbuddy, Whatzzzup'
print(s)

